name: Micro Frontend- Non Prod
on:
  push:
    branches: [master]
env:
  VERCEL_ORG_ID: team_GUvz6YdFYkgxVl5oza8UF4u3

jobs:
  cicd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - run: npm i

      #- run: npm run test

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Deploy Next
        working-directory: nextjs-mfe-remote
        env:
          VERCEL_PROJECT_ID: prj_8vB90ZYpHvvcPD9JjEVNN9MlPKZr
        run: |
          vercel pull --yes --environment=preview --token=OHOXMiusFe2TGYMFkoPNDL2Z
          vercel build --token=OHOXMiusFe2TGYMFkoPNDL2Z 
          echo "NEXT_URL=$(vercel deploy --token=OHOXMiusFe2TGYMFkoPNDL2Z)" >> $GITHUB_ENV
